(() => {
  const defaultLocale = "en-US";
  const localeKey = "verba-interface-language";
  const resources = {};
  const aliases = { newTranslation: "nav.newTranslation", workspace: "nav.workspace", workspaceTranslate: "nav.translationStudio", history: "nav.history", glossaryNav: "nav.glossary", recent: "nav.recent", settings: "nav.settings", plan: "nav.plan", help: "nav.help", madeFor: "studio.madeFor", heroTitle: "studio.heroTitle", heroDescription: "studio.heroDescription", chooseStyle: "studio.chooseStyle", whereUsed: "studio.whereUsed", modeTip: "studio.modeTip", emailMode: "studio.email", emailDesc: "studio.emailDescription", chatMode: "studio.chat", chatDesc: "studio.chatDescription", clear: "studio.clear", paste: "studio.paste", translationLabel: "studio.translation", nativeTone: "studio.nativeTone", meaningLabel: "studio.meaning", regenerate: "studio.regenerate", copy: "studio.copyTranslation", translateHint: "studio.translateHint", translate: "studio.translate", apiSettings: "api.title", translationSetup: "api.setup", providerTitle: "api.chooseProvider", providerDescription: "api.providerDescription", envSaved: "api.keysSavedLocal", saveProvider: "api.useProvider", glossaryTitle: "glossary.title", glossaryDescription: "glossary.description", addTerm: "glossary.add", sourceTerm: "glossary.source", targetTerm: "glossary.target", settingsSaved: "glossary.savedLocal", saveGlossary: "glossary.save", apiKeys: "api.keysTitle", apiKeyDescriptionTitle: "api.keysTitle", apiKeyDescription: "api.keysDescription", keysLocal: "api.keysSavedLocal", saveKeys: "api.saveKeys" };
  let locale = localStorage.getItem(localeKey) || (navigator.language?.toLowerCase().startsWith("zh") ? "zh-CN" : defaultLocale);
  function valueFor(key, selectedLocale = locale) { return key.split(".").reduce((value, part) => value?.[part], resources[selectedLocale]) ?? key.split(".").reduce((value, part) => value?.[part], resources[defaultLocale]); }
  function t(key, values = {}) { const resolvedKey = aliases[key] || key; const value = valueFor(resolvedKey); if (typeof value !== "string") { if (location.hostname === "localhost") console.warn(`Missing i18n key: ${resolvedKey}`); return ""; } return value.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? ""); }
  function apply(root = document) { root.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); }); root.querySelectorAll("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); }); root.querySelectorAll("[data-i18n-aria-label]").forEach((element) => { element.setAttribute("aria-label", t(element.dataset.i18nAriaLabel)); }); [["#historyTitle", "history.title"], ["#historySearch", "history.searchPlaceholder", "placeholder"], ["#appSettingsTitle", "nav.settings"], ["#appSettingsOverlay h3", "updates.title"], ["#checkUpdates", "updates.check"], ["#installUpdate", "updates.install"]].forEach(([selector, key, attribute]) => { const element = root.querySelector(selector); if (element) attribute ? element.setAttribute(attribute, t(key)) : element.textContent = t(key); }); root.querySelectorAll(".close-settings").forEach((button) => button.setAttribute("aria-label", t("common.close"))); const model = root.querySelector(".model-management"); if (model) { const heading = model.querySelector("strong"); const description = model.querySelector(".model-management-heading p"); const labels = model.querySelectorAll(".model-toggle"); if (heading) heading.textContent = t("api.autoModels"); if (description) description.textContent = t("api.autoModelsDescription"); if (labels[0]) labels[0].lastChild.textContent = ` ${t("api.manualOverride")}`; if (labels[1]) labels[1].lastChild.textContent = ` ${t("api.allowHighCost")}`; const save = model.querySelector("#saveModelOverride"); const refresh = model.querySelector("#refreshModels"); if (save) save.textContent = t("api.saveModel"); if (refresh) refresh.textContent = t("api.checkModels"); } document.documentElement.lang = locale; document.title = `Verba — ${t("nav.translationStudio")}`; }
  async function setLocale(nextLocale) { locale = nextLocale === "zh-CN" ? "zh-CN" : defaultLocale; localStorage.setItem(localeKey, locale); apply(); window.dispatchEvent(new CustomEvent("verba:locale-changed", { detail: { locale } })); }
  const ready = Promise.all(["zh-CN", "en-US"].map(async (name) => { resources[name] = await fetch(`locales/${name}.json`).then((response) => response.json()); })).then(() => { apply(); });
  window.VerbaI18n = { ready, t, apply, setLocale, get locale() { return locale; }, error: (code) => t(`errors.${code || "UNKNOWN"}`) || t("errors.UNKNOWN") };
})();
