const {app,BrowserWindow}=require('electron');const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{pathToFileURL}=require('url');const out='acceptance/layout-1.1.4';fs.mkdirSync(out,{recursive:true});const profile=fs.mkdtempSync(path.join(os.tmpdir(),'verba-layout-'));app.setPath('userData',profile);let server;
app.whenReady().then(async()=>{const root=process.argv[2]?path.resolve(process.argv[2]):process.cwd();server=await (await import(pathToFileURL(path.join(root,'server.mjs')).href)).startServer({publicDirectory:root,configurationDirectory:profile,port:0});const win=new BrowserWindow({show:false,width:1440,height:1000,webPreferences:{offscreen:true,backgroundThrottling:false,contextIsolation:true,nodeIntegration:false,sandbox:true}});await win.loadURL('http://127.0.0.1:'+server.address().port);const js=s=>win.webContents.executeJavaScript(s);await js('VerbaI18n.ready');await new Promise(r=>setTimeout(r,400));
const base='您好，关于上周提交的账户问题，我想补充一些情况。请核查交易记录，并告知目前的处理进展。我们需要确认到账金额及相关日期，避免重复提交申请。';const medium=(base+'\n\n').repeat(8).slice(0,500);const long=(base+'\n\n').repeat(20).slice(0,1000);const short='Hello\n\nThank you.';const results=[];
const settle=()=>new Promise(r=>setTimeout(r,180));
const metrics=()=>js(`(()=>{const s=document.querySelector('#sourceText'),t=document.querySelector('#translatedText');return {sourceHeight:s.clientHeight,sourceScroll:s.scrollHeight,resultHeight:t.clientHeight,sourceTop:s.getBoundingClientRect().top,resultTop:t.getBoundingClientRect().top,value:s.value,maxLength:s.maxLength,overflow:Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)>innerWidth,scrollY,selection:s.selectionStart};})()`);
for(const width of [1440,900,580,390]){win.setSize(width,1000);await settle();for(const [name,text] of [['short',short],['500',medium],['1000',long]]){await js(`document.querySelector('#sourceText').value=${JSON.stringify(text)};document.querySelector('#sourceText').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#translatedText').textContent=${JSON.stringify((base+'\n\n').repeat(name==='short'?1:12))};`);await settle();let m=await metrics();assert.equal(m.value,text);assert.equal(m.maxLength,1000);assert.ok(m.sourceScroll<=m.sourceHeight+1,JSON.stringify({width,name,m}));assert.equal(m.overflow,false,JSON.stringify({width,name,m}));if(width>620){assert.ok(Math.abs(m.sourceHeight-m.resultHeight)<=1);assert.ok(Math.abs(m.sourceTop-m.resultTop)<=1);}results.push({width,name,...m});if(width===1440&&name==='500'){await js(`document.querySelector('#sourceText').scrollIntoView({block:'start'})`);await settle();fs.writeFileSync(out+'/desktop.png',(await win.webContents.capturePage()).toPNG());}if(width===390&&name==='1000'){await js(`document.querySelector('#sourceText').scrollIntoView({block:'start'})`);await settle();fs.writeFileSync(out+'/narrow.png',(await win.webContents.capturePage()).toPNG());}}
await js(`document.querySelector('#clearText').click()`);await settle();const cleared=await metrics();assert.ok(cleared.sourceHeight<=172);results.push({width,name:'clear',...cleared});}
win.setSize(1440,1000);await js(`document.querySelector('[data-mode=email]').click();document.querySelector('#swapLanguages').click();document.dispatchEvent(new CustomEvent('verba:restore-history',{detail:{mode:'email',direction:'zhToEn',source:${JSON.stringify(medium)},translation:'Restored translation.',englishMeaning:'',strategyVersion:'customer-email-zh-en/v1',sourceNotes:[],status:'translated'}}));`);await settle();let before=await metrics();assert.equal(before.value,medium);await js(`VerbaEmailView.render({sourceNotes:[{message:${JSON.stringify(base.repeat(20))},sourceQuote:'合成布局测试'}],status:'translated'});`);await settle();assert.equal((await metrics()).sourceHeight,before.sourceHeight);
await js(`document.querySelector('#sourceText').focus({preventScroll:true});document.querySelector('#sourceText').setSelectionRange(20,20);window.scrollTo(0,350);document.querySelector('#sourceText').dispatchEvent(new Event('input',{bubbles:true}));`);await settle();let stable=await metrics();assert.equal(stable.selection,20);assert.ok(Math.abs(stable.scrollY-350)<=1);
fs.writeFileSync(out+'/checks.json',JSON.stringify({passed:true,root,modelCalls:0,historyPreservesText:true,notesExcludedFromBodyHeight:true,caretStable:true,pageStable:true,results},null,2));win.destroy();server.close();app.quit();}).catch(e=>{console.error(e);server?.close();app.exit(1)});
